### ISSUE TITLE
Checklist for call for topics

### ISSUE THREAD

**Issue by kevintanhongann** [kevintanhongann/myjug-memo#1]
Topics that can be presented goes here. Need to annotate the events to happen either ONLINE or OFFLINE.

- [ ] Micronaut in action (ONLINE)

- [ ] Play Framework in action

- [ ] Changes in JDK 12

- [ ] Vert.x in action

- [ ] Java in Data Science https://www.datasciencecentral.com/profiles/blogs/10-popular-java-machine-learning-tools-libraries
